services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: 1000:1000  # Replace with actual UID and GID
    network_mode: 'host'  # Host mode for better performance
    volumes:
      - jellyfin-config:/config  # Automatically created volume for configuration
      - jellyfin-cache:/cache  # Automatically created volume for cache
      - /mnt/localdisk1:/media  # Primary media library
      - /mnt/localdisk1/media-secondary:/media2:ro  # Secondary media library (read-only)
      - /mnt/localdisk1/font:/usr/local/share/fonts/custom:ro  # Custom fonts for subtitles (read-only)
    environment:
      - TZ=Asia/Manila  # Set your timezone
      - JELLYFIN_PublishedServerUrl=https://flix.jhenbert.pro  # Optional: Custom server URL for discovery
      - NVIDIA_DRIVER_CAPABILITIES=all  # Enable all NVIDIA GPU capabilities
      - NVIDIA_VISIBLE_DEVICES=all  # Make all GPUs visible to the container
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      #runtime: nvidia  # Use NVIDIA container runtime for GPU acceleration

volumes:
  jellyfin-config:  # Automatically created volume for Jellyfin configuration
  jellyfin-cache:   # Automatically created volume for Jellyfin cache
